### PR TITLE
Fixes #67: adds new `--paper-tab-content-unselected` mixin

### LINKED ISSUE #67: Feature request: Control opacity on elements not selected
This is a request to remove or have some kind of control over(when not used in a custom element):

```css
    :host(:not(.iron-selected)) > .tab-content {
      opacity: 0.8;
    }
```

### PR DESCRIPTION
**Pull request by bicknellr**

### CODE REVIEW

**Comment by cdata** [comment]
LGTM :+1:

**Comment by abdonrd** [comment]
What are the .swp?

**Comment by bicknellr** [comment]
@abdonrd Vim swap files... they've been removed. (And I now have `*.sw?` in my global .gitignore.)

**Comment by abdonrd** [comment]
@bicknellr ok, thanks! :D

**Pull request merged**
