### PR TITLE
Fixed align-bottom demo

### PR DESCRIPTION
**Pull request by GabiAxel**

### CODE REVIEW

**Comment by notwaldorf** [comment]
This looks great! There's also an `paper-tabs[alignBottom]` style on L54. Would you mind fixing that as well, please? Thanks!

**Comment by GabiAxel** [comment]
@notwaldorf Done.

**Comment by notwaldorf** [comment]
Arg, and one more thing before I can merge this: would you mind squashing your commits, please? Thanks!

**Comment by GabiAxel** [comment]
@notwaldorf Squashed.

**Comment by notwaldorf** [comment]
Thanks! :+1:

**Pull request merged**
