### PR TITLE
Fixes #132. Fix truncated documentation by escaping @ sign.

### LINKED ISSUE #132: paper-tabs docs are truncated

### PR DESCRIPTION
**Pull request by arthurevans**
Sadly, there doesn't seem to be a better way to do this.

### CODE REVIEW

**Comment by notwaldorf** [comment]
@arthurevans Does it work if you just escape the `@`? Or do we have to escape everything? If this is the only way, then LGTM (docs >> no docs)

**Comment by arthurevans** [comment]
I tested, and unfortunately, if you use the entity inside a markdown code block, it shows up as `&#64;` in the doc output. And if we put it in a normal `<pre>` block, we need to escape the start tags (could escape the end tabs too, but this world and I'm lazy. 

We should add this limitation to the doc guide, because it's sneaky.

**Comment by bicknellr** [comment]
How does hydrolysis handle triple-backticked code? Could we just put it in that?

**Comment by arthurevans** [comment]
I just tested the triple backtick, and the results were identical to a standard markdown code block: `&#64;` gets escaped, and shows up verbatim; `@` truncates the doc (leaving behind a single set of backticks all alone on the last line:

\`\`\`

**Comment by bicknellr** [comment]
Alrighty, merging then.

**Pull request merged**
