### PR TITLE
Use 0.9 down/up gestures

### PR DESCRIPTION
**Pull request by azakus**
Remove trackstart event handler
Fix scroll handler name to _scroll

### CODE REVIEW

**Comment by cdata** [comment]
This LGTM. Did you happen to run the tests?

**Comment by azakus** [comment]
Yep, the tests were passing for me.

**Comment by cdata** [comment]
It looks like you need to rebase.

**Comment by azakus** [comment]
rebased

**Comment by cdata** [comment]
LGTM :+1:

**Pull request merged**
