### PR TITLE
Add type annotation for `selected`

### PR DESCRIPTION
**Pull request by jakemac53**
It can actually be either a string or a number (index)

### CODE REVIEW

**Comment by jakemac53** [comment]
ping?

**Comment by bicknellr** [comment]
I wonder if `selected` should just be removed from the properties list of `paper-tabs` altogether. It's really inherited all the way from `IronSelectableBehavior`, which should maintain the canonical docs for that property.

**Comment by jakemac53** [comment]
That seems reasonable to me as well.

**Comment by bicknellr** [comment]
Yeah, talked with @notwaldorf, sounds like removing it completely is the right way to go. The docs generator should still surface `selected` on the `paper-tabs` page.

**Pull request closed without merging**
