### PR TITLE
making it registrable and availalbe for webjars

### PR DESCRIPTION
**Pull request by sergiuszkierat**
I would like to register this package on bower to access through [webjars](http://www.webjars.org/bower).

### CODE REVIEW

**Comment by sergiuszkierat** [comment]
I signed CLA

**Comment by morethanreal** [comment]
@taylor, are we continuing to intentionally not register packages on bower?

**Comment by cdata** [comment]
@justinfagnani can you provide details on how to get packages published to `npm`?

**Comment by justinfagnani** [comment]
paper-tabs is already published to npm at `@polymer/paper-tabs`. Not sure what that has to do with this though? I'm not sure what webjars are.

**Comment by sergiuszkierat** [comment]
> I'm not sure what webjars are.

@justinfagnani, take a look at [webjars](http://www.webjars.org/)

> Deployed! It will take a few hours for the Maven Central index to update but you should be able to start using the NPM WebJar now.
> GroupID = org.webjars.npm
> ArtifactID = paper-tabs
> Version = 0.0.0

BTW, the version is quite strange :)

**Comment by justinfagnani** [comment]
Where did that version come from? All the elements should be at version 0.0.3 in npm right now.

**Comment by justinfagnani** [comment]
See: https://www.npmjs.com/package/@polymer/paper-tabs

**Comment by sergiuszkierat** [comment]
The [NPM WebJars](http://www.webjars.org/npm) retrieves data from the official public npm registry.
Take a look at http://registry.npmjs.org/paper-tabs. There is only one incorrect version, i.e. 0.0.0

**Comment by justinfagnani** [comment]
I should delete the un-scoped paper-tabs. All of our official packages are under the @polymer scope.

**Pull request closed without merging**
